pagopa/arc-fe

src/App.tsx
- Basic theme override
- Set default background color as white
- Set paper background color as #F5F5F5
=> feat: [P4ADEV-161] mui theme override

.eslintignore, .gitignore, package.json, src/components/TransactionDetail.tsx, src/routes/Transaction.tsx, src/stories/footer.stories.tsx
The goal of this PR is drop the "cache" from parcel to enhance the DX.
I fix also some small issues within the project 
- add no-cache to parcel dev
- move footer storybook story to the correct folder
- refine git ginore
=> feat: [p4adev-212] Remove cache in parcel and other stuffs

.eslintignore, .storybook/preview.tsx, __mocks__/fileMock.js, __mocks__/styleMock.js, jest.config.ts, package.json, src/components/Alerts/IOAlert.test.tsx, src/components/Alerts/IOAlert.tsx, src/global.d.ts, src/routes/Dashboard.tsx, src/stories/alerts.stories.tsx, src/translations/it/translations.json, src/utils/config.test.ts, src/utils/config.tsx
- IOAlert component created and styled
- IOAlert component added to dashboard
- Translation file updated
- Added storybook story
- href to 'https://uat.checkout.pagopa.it/' added to main "New Payment" button in dashboard
These are required changes in order to build the main route ("Dashboard")
Tested visually and manually via local development server
=> feat: [P4ADEV-204] Info alert added to dashboard route

.github/workflows/deploy_storybook_develop.yml, .gitignore, .storybook/manager-head.html
This PR create a static version of Storybook to publish on GH pages (develop branch)
- Add action
Obtain a static copy of Storybook
=> feat: [P4ADEV-202]  storybook on pages

.github/workflows/deploy_storybook_develop.yml
Optimize storybook build command
=> fix: Optimize storybook build command

.github/workflows/deploy_storybook_develop.yml
Change command for storybook action
=> fix: Change command for storybook action

src/App.tsx, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/Breadcrumbs/breadcrumbs.test.tsx, src/components/Header/Header.test.tsx, src/components/Header/index.tsx, src/components/Layout.tsx, src/models/Breadcrumbs.ts, src/routes/Transaction.tsx, src/routes/User.tsx, src/routes/routes.ts, src/translations/en/translations.json, src/translations/it/translations.json, src/utils/config.tsx
- adds static User page
- sidebar visibility can be setted using the browserRouter object
- adds navigation to breadcrumb and Header account action
This pr adds the User route ui/ux to the app. The data is static and the ui target only a desktop resolution.
Visual testing
=> feat: [P4ADEV-208] User Data page

src/App.tsx, src/routes/Dashboard.tsx, src/translations/it/translations.json, src/utils/converters.test.ts, src/utils/converters.ts, src/utils/index.ts, src/utils/loaders.ts
- GET /transactions API call implemented
- added data transformer and converter utilities
- unit tests added 
Static data needs to be replaced by data returned by services trough BE component (we are using a BE mock in this phase)
Tested locally using BE mock service and unit test
=> feat: [P4ADEV-272] GET /transactions

src/components/Transactions/Transaction.tsx, src/components/Transactions/TransactionDetail.tsx, src/components/Transactions/transactions.test.tsx, src/routes/routes.ts, src/stories/utils/mocks.tsx, src/utils/converters.test.ts, src/utils/datetools.test.ts, src/utils/datetools.ts, src/utils/index.ts, src/utils/loaders.ts
This PR try to enhance the work done in the PR #24 abstracting date management and powering nav.
- add date tool
- add test
- add navigate between transactions
=> fix: [P4ADEV-206] enhancement for PR #24

.env, README.md, jest.config.ts, src/App.tsx, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/Transactions/Transaction.tsx, src/components/Transactions/TransactionDetail.tsx, src/components/Transactions/transactions.test.tsx, src/models/Breadcrumbs.ts, src/routes/Dashboard.tsx, src/utils/converters.test.ts, src/utils/converters.ts
- Click on transaction row to see details
- added "see all transactions" action
- fixed breadcrumb for "my data"
- deleted quiettance button
=> fix: [P4ADEV-295] Bug fixing.

src/App.tsx, src/components/Sidebar/Sidebar.tsx, src/components/Sidebar/SidebarMenuItem.tsx, src/components/Transactions/Transaction.tsx, src/routes/Dashboard.tsx, src/routes/TransactionsList.tsx, src/routes/User.tsx, src/translations/it/translations.json
This PR solves several tips of accessibility.
- Mod sidebar using the right _roles_ attributes
- Mod transactions and relative filter
- Mod user-data page according a correct enum of heading tags
- Mod transaction view
enhance accessibility 
- unit test
- google lighthouse plugin
=> feat: [P4ADEV-293]  enforce accessibility

src/App.tsx, src/routes/TransactionsList.tsx, src/utils/loaders.ts
Integrated API mock for transaction list.
Visual testing.
=> feat: [P4ADEV-309] Integrated be mock for transaction list

package.json, src/routes/Dashboard.tsx, src/utils/converters.test.ts, src/utils/index.ts, src/utils/loaders.ts, ts-to-zod.config.js, yarn.lock
- yarn generate command updated
- zod schemes auto generated by types derived from the api specs
- all schemes exposed by the global utility object 
Trought this implementation the response can be validate by a zod schema to be sure we are receiving exactly what is expected (declared in the swagger). The schemes are autogenerated using types/interfaces derivated by the specs.
Using the BE mock service and changing temporary the type of some properties, the FE brokes (as expected)
=> breaking: [P4ADEV-297] run time type check with zod

src/components/Layout.tsx, src/components/Transactions/Transaction.test.tsx, src/components/Transactions/Transaction.tsx, src/components/Transactions/Transactions.tsx, src/components/Transactions/transactions.test.tsx, src/routes/Dashboard.tsx
Added a set of css rules to make the storico's table full responsive and usable at lower resolution
The UI system we use is responsive by default. Despite everything, some effort is required to ensure a more adequate behavior and adherence to the designed layout
Using storybook to visual inspect in isolation the component's behaviour
=> feat: [P4ADEV] storico's table responsiveness

src/App.tsx, src/components/Alerts/IOAlert.tsx, src/components/BackButton/BackButton.test.tsx, src/components/BackButton/BackButton.tsx, src/components/BackButton/index.ts, src/components/Breadcrumbs/Breadcrumbs.tsx, src/components/Breadcrumbs/breadcrumbs.test.tsx, src/components/Footer.test.tsx, src/components/Layout.tsx, src/components/Transactions/Transaction.tsx, src/components/Transactions/TransactionDetail.tsx, src/models/Breadcrumbs.ts, src/routes/Dashboard.tsx, src/translations/it/translations.json, src/utils/style.tsx
- Breakproints definition
- Dashboard style fixes
- Dashboard mobile styles
- TransactionDetail intro content styling
- BackButton refactored as separate component
- Routing handle refactoring
- Breadcrumbs mobile styling
- Footer test import fix
- Breadcrumbs unit tests
- BackButton unit tests
This pr updates style changes and add responsiveness to layout elements
- unit tests
=> feat: [P4ADEV-312] Mobile layout and styling

.github/workflows/pr-title-check.yml, src/App.tsx, src/components/ErrorBoundary/ErrorBoundary.test.tsx, src/components/ErrorBoundary/ErrorBoundary.tsx, src/components/ErrorBoundary/index.tsx, src/components/ErrorFallback/ErrorFallback.test.tsx, src/components/ErrorFallback/ErrorFallback.tsx, src/components/ErrorFallback/index.tsx, src/components/HealthCheck/HealthCheck.test.tsx, src/components/HealthCheck/HealthCheck.tsx, src/components/HealthCheck/index.tsx
- Updates pr titlecheck regex
- ErrorBoundary component
- ErrorFallback component
- HealthCheck as component
- routing bubbles uncaught
errors up for undefined (*)
and root (/) routes
- unit tests
Create a boundary component that can handle any runtime errors to provide the browser with a custom page instead of the default one.
visual testing
unit tests
=> feat: [P4PU-96] Error Boundary

src/components/ErrorBoundary/ErrorBoundary.tsx, src/index.tsx
Added interceptor for error handling and handled case for error 401.
=> feat: [P4PU-92] 401 Unauthorized

src/components/Sidebar/Sidebar.tsx, src/components/Transactions/Transaction.tsx, src/components/Transactions/Transactions.tsx, src/routes/Dashboard.tsx
Refactored components:
- Sidebar
- Transaction
- Transactions
- Dashboard
This pr reduces the usage of mui useMediaQuery for the purpose of readability and rendering performance.
Another approach could be creating an hook exposing all the available breakpoints, but this could cause unnecessary rerendering and incompatibilities with SSR if considered in the future.
- unit tests
=> feat: [P4PU-95] useMediaQuery

src/utils/config.tsx
Changed "Area Riservata Cittadini" with pagoPA logo.
This change is required by the change in design.
Visual testing
=> feat: [P4PU-176] Added header logo

src/components/Layout.tsx, src/routes/User.tsx
Added mobile responsiveness and adapted layout to design changes
This change is required by the change in design.
Visual testing.
=> feat: [P4PU-177] added mobile responsiveness and merged user info boxes.

src/App.tsx, src/components/Footer.tsx, src/routes/Login.tsx, src/routes/routes.ts, src/translations/it/translations.json
Created static page for login
This change is required by design
Visual testing and Jest.
=> feat: [P4PU-173] login page

.env, README.md, src/App.tsx, src/components/BackButton/BackButton.tsx, src/components/Layout.tsx, src/models/Breadcrumbs.ts, src/routes/Assistance.tsx, src/routes/routes.ts, src/translations/it/translations.json
Added post login assistance page.
This is required by the designers.
Visual testing.
=> feat: [P4PU-174] post login assistance

.env, .jest/setEnvVars.js, README.md, jest.config.ts, src/components/Transactions/Transaction.tsx, src/components/Transactions/TransactionDetail.tsx, src/components/Transactions/Transactions.tsx, src/utils/config.test.ts, src/utils/config.tsx
- added a new env variable (SHOW_STATUS_INFO) to hide or show the status info in the whole application
- added a runtime type checking of env variables to ensure compatible values and have a feedback if not (trough zod)
- added unit tests
Status info will be introduced after, but we prefer to turn on/off the relative UI instead of commenti/eliminating code
Tested locally changing the env variables in the .env file and running/checking the FE subsequently
=> feat: [P4PU-195] Status info (transaction status) removal by config

.proxyrc, src/components/PaymentNotice/Empty.test.tsx, src/components/PaymentNotice/Empty.tsx, src/components/PaymentNotice/Error.tsx, src/components/PaymentNotice/List.tsx, src/components/PaymentNotice/PaymentNotice.tsx, src/routes/PaymentNotices.tsx, src/translations/it/translations.json, src/utils/loaders.ts
Added empty state and error state component and logic to payment notices page.
This change is required by design.
Unit testing, visual testing.
=> feat: [P4PU-213] Error and Empty state for payment notices route. 

src/utils/converters.test.ts, src/utils/converters.ts
This PR enforce the manage of the "amount" in euro using intl function.
- refact of toEuro function
Rif. jira P4PU-225
=> feat: [P4PU-225] Refact of toEuro function

src/routes/TransactionsList.tsx
Fixes filtering on registeredByMe transactinos
Previously regiteredByMe transaction tab was filtered as not payedByme transactions.
=> fix: [P4PU-236] transactions tab filter

src/components/Transactions/Transactions.tsx, src/hooks/useNormalizedTransactions.test.tsx, src/hooks/useNormalizedTransactions.tsx, src/routes/Dashboard.tsx, src/routes/TransactionsList.tsx, src/stories/tabs.stories.tsx, src/stories/utils/mocks.tsx, src/translations/it/translations.json, src/utils/converters.test.ts
- fixes filtering of the transaction tabs
- fixed table height
- refactored transaction splitting logic as an hook
- fixed typo payed -> paid where possible (It should be fixed on the backend)
- unit tests
Previously there was a concatenation of `payedByMe` and `registeredByMe` transaction, which caused a duplication since this two properties are independent from each other. Also refactored the filtering logic as an independent hook so to unit test it.
- unit tests
=> fix: [P4PU-253] transactions all tab filter

.devops/deploy-pipelines.yml, .devops/local-templates/setup-env.yaml, .env, .jest/setEnvVars.js, src/components/PaymentButton/PaymentButton.test.tsx, src/components/PaymentButton/index.tsx, src/components/QueryLoader/index.tsx, src/components/QueryLoader/queryLoader.test.tsx, src/components/Transactions/Empty.test.tsx, src/components/Transactions/Empty.tsx, src/components/Transactions/Retry.test.tsx, src/components/Transactions/Retry.tsx, src/components/Transactions/Transaction.test.tsx, src/components/Transactions/index.tsx, src/components/Transactions/transactionDetail.test.tsx, src/components/Transactions/transactions.test.tsx, src/hooks/useNormalizedTransactions.tsx, src/routes/Dashboard.tsx, src/routes/TransactionsList.tsx, src/translations/it/translations.json, src/utils/config.tsx, src/utils/converters.test.ts, src/utils/converters.ts
- Added an 'Empty' component to be showed when the transaction list is empty
- Added a 'Retry' component to be showed when the transaction list fetch fails and gives the user the possibility to retry
- Empty and Retry component managed in Dashboard (home page) and transactions list page
- 'Payment button' created (and tested) to to encourage reuse
- translation file updated
- a small refactor about the exports for the folder src/components/Transactions
Errors and edge cases management
Tested through local development server and temporary mocks
=> feat: [P4PU-237] transactions list empty state and retry

src/components/PaymentNotice/Card.tsx, src/components/PaymentNotice/List.tsx, src/utils/loaders.ts
Added expiring date label for every row.
In this phase we only have the single installment option, with an expiring date. 
=> fix: [P4PU-257] Payment notices list uniformation

src/utils/converters.test.ts, src/utils/converters.ts
=> fix: [P4PU-256] added - instead of 0 for unavailable amount

src/components/PaymentNotice/List.tsx, src/components/Transactions/TransactionDetail.tsx, src/utils/converters.ts, src/utils/datetools.test.ts, src/utils/datetools.ts, src/utils/index.ts
- adds formatDate function, wrapping
toLocaleString for date formatting
- unit tests
- unit tests
=> feat: [P4PU-226] date format

src/components/Transactions/TransactionDetail.tsx, src/models/TransactionDetail.ts, src/stories/utils/mocks.tsx, src/translations/it/translations.json, src/utils/converters.ts
Adapted transaction details to new igma
Required by design.
=> feat: [P4PU-279] transaction details update

src/routes/User.tsx, src/translations/it/translations.json
Adapted responsiveness to new design specifications. 
Changed some fields that were different from the new specifications. 
Visual and unit testing
=> feat: [P4PU-265] My data responsiveness adaptation

src/components/Transactions/TransactionDetail.tsx, src/components/Transactions/transactionDetail.test.tsx, src/models/TransactionDetail.ts, src/stories/utils/mocks.tsx, src/utils/config.tsx, src/utils/converters.ts
- Conditional rendering of the payer, payment method info and account holder sections
- Unit test added
For privacy reasons the payer info, payment method and account holder aren't always available. When this occurs the relative section must be hidden
Tested inspecting manually the UI and via unit test
=> feat: [P4PU-271] transaction details conditional rendering

src/utils/converters.test.ts, src/utils/converters.ts
=> fix: [P4PU-251] trimmed tax codes for cdn link.

src/components/PaymentNotice/Card.test.tsx, src/components/PaymentNotice/Card.tsx, src/components/PaymentNotice/Detail.tsx, src/components/PaymentNotice/List.tsx, src/components/Transactions/Transactions.tsx, src/routes/Assistance.tsx, src/routes/Dashboard.tsx, src/routes/Login.tsx, src/translations/it/translations.json
=> feat: [P4PU-209] translations rationalization

.jest/setup.js, jest.config.ts, package.json, src/components/Layout.tsx, src/components/Modals/AssistanceBackModal.tsx, src/components/Modals/PullPaymentsModal.tsx, src/components/Modals/index.tsx, src/components/Modals/modals.test.tsx, src/components/PaymentNotice/Card.test.tsx, src/components/PaymentNotice/Card.tsx, src/components/PaymentNotice/Detail.test.tsx, src/components/PaymentNotice/Preview.tsx, src/index.tsx, src/routes/Assistance.tsx, src/routes/Dashboard.tsx, src/routes/PaymentNotices.tsx, src/translations/it/translations.json, src/utils/index.ts, src/utils/loaders.ts, src/utils/modal.tsx, src/utils/storage.ts, yarn.lock
- Added the functionality to allow users to view their payment list only after expressing explicit consent (opt-in)
- Added the necessary UI (consent modale) and the storage logics (by session storage)
- Introduced signals to simply the global state management
- Refactoring of the modal's working
- Added new unit test
This change is required to assolve policy and design requirements
Major of the functionality and UI behaviour tested by unit test, manual testing
=> feat: [P4PU-210] pull payments, opt-in

.devops/deploy-pipelines.yml, CODEOWNERS
The deployment is performed on a private agent pool because the storage account has been requested to be private.
=> fix: Devops deploy

package.json
- swagger file pointer updated in the package.json file
Change required to generate correctly the 'API client'
Manually trying to generate the 'API client' (yarn generate) and running the FE (yarn start)
=> fix: [P4PU-334] swagger file pointer updated

src/hooks/useNormalizedTransactions.test.tsx, src/hooks/useNormalizedTransactions.tsx, src/utils/converters.test.ts
- fixes payed in paid in app logic and tests
Typo fix
Visual testing and unit tests
=> fix: [P4PU-278] fixes typo

.devops/deploy-pipelines.yml, .gitignore
=> fix: [P4PU-343] Deploy on public storage account

src/App.tsx, src/routes/Login.tsx
With this PR we set a FE guard to prevent navigation if the user hasn't the `sessionToken` setted
- add guard component
- set a temp workaround to bypass guard
- see JIra
=> feat: [P4PU-333] FE guards

.github/workflows/deploy_storybook_develop.yml, .storybook/main.ts, package.json
- prepended yarn generate step to storybook build phase (required)
- fix a problem with process.env and vite to make env variables available
The github action used to deploy storybook failed regularly due to a problem with the build process
Tested triggering manually the build step (yarn build-storybook)
=> fix: [P4PU-337] storybook deploy and env variables fix

src/App.tsx, src/hooks/useQueryParams.test.tsx, src/hooks/useQueryParams.tsx, src/routes/AuthCallback.tsx, src/routes/routes.ts
This PR add a new route called `auth_callback` rendered after the login with some useful query params.
It's a WIP cause we need new info to manage login and redirection.
- add route
- create a hook to manage query params
- dummy page
See jira
=> feat: [P4PU-186] Add route to manage auth_callback and query paramas

.jest/setup.js, src/components/Header/Header.test.tsx, src/components/Header/index.tsx
This PR adds a function to the "logout button" for clear storage and redirect the user to the login-page
- add a function
- write a test
=> feat: [P4PU-229] add logout function

src/utils/converters.ts
Finished implementing the centralized missing value when a value is not returned from the API.
This change makes it easier to modify the character representing the missing value in the future. 
=> feat: [P4PU-275] Implemented missing value from utils.

src/utils/config.tsx
The logo icon on the header now redirects the user to the homepage.
This change is required by the designers.
=> feat: [P4PU-296] Homepage link on header

src/components/Sidebar/sidebar.styles.ts
Fixed sidebar behaviour. 
The hamburger button now stays on the bottom of the page, and the menu sticks on the screen.
This is required by the designers.
=> fix: [P4PU-297] Sidebar height

.github/workflows/sonar.yml, sonar-project.properties
Added sonar cloud scan to github actions
Sonar cloud helps in detecting common mistakes, bugs & security vulnerabilities.
Triggering the action manually and automatically (on pull request)
=> chore: [P4PU-182] sonar cloud

src/components/Skeleton/UserInfo.tsx, src/components/Skeleton/index.ts, src/components/Skeleton/skeleton.test.tsx, src/routes/User.tsx, src/utils/loaders.test.tsx, src/utils/loaders.ts
Integrated User info api
Visual and unit testing
=> feat: [P4PU-352] Integrated userinfo

src/components/PaymentNotice/Card.tsx, src/components/PaymentNotice/List.tsx, src/translations/it/translations.json
All the container of a payment notice must be clickable
- create a function for onClick
- improve accessibility isses
=> fix: [P4PU-312] Refact as a function.

src/components/AssistanceForm/AssistanceForm.test.tsx, src/hooks/usePersistentSignal.test.ts, src/hooks/usePersistentSignal.ts, src/store/PaymentNoticeStore.tsx
- usePersistentSignal can be used with sessionStorage
- PaymentNoticeStore uses sessionStorage
- unit tests
=> feat: [P4PU-427] usePersistentSignal storage refactoring

src/hooks/useUserEmail.test.tsx, src/hooks/useUserEmail.tsx
=> chore: [P4PU-426] Created user email hook

src/components/Tabs/index.tsx
This PR modify the tabs of "transactions" for support "scroll" when in mobile viewport
- add specific attributes to Tabs
Solve the issue
=> fix: [P4PU-311] set scrollable tabs

src/components/Sidebar/Sidebar.tsx, src/components/Sidebar/SidebarMenuItem.tsx
Fixed sidebar item height during the expansion transition. 
This change is required by the designers
Visual testing.
=> fix: [P4PU-298] fixed sidebar item height

src/index.html
Changed application title
The title needed to be changed because it was a placeholder.
=> chore: [P4PU-429] Changed application title.

src/components/Transactions/Transaction.tsx
=> fix: [P4PU-301] added hover on table rows.

src/routes/User.tsx, src/translations/it/translations.json
Removed channel code field from my data page
The channel code was in the figma by mistake, so it needed to be removed.
=> fix: [P4PU-230] Removed channel code from my data

src/components/Transactions/Transactions.tsx
Fixed container height for transaction list
=> feat: [P4PU-304] Fixed container height for transaction list.

src/routes/AuthCallback.tsx
Implemented loading spinner during login
=> feat: [P4PU-432] implemented loading spinner

.proxyrc, src/components/Tabs/index.tsx
Fixed tab spacing.
A previous PR caused a bug in the Tab spacing.
=> fix: [P4PU-305] tab spacing

src/components/Header/Header.test.tsx, src/components/Header/index.tsx, src/hooks/useUserInfo.test.tsx, src/hooks/useUserInfo.tsx, src/models/User.ts, src/routes/User.tsx, src/store/GlobalStore.tsx, src/store/PaymentNoticeStore.tsx, src/store/UserInfoStore.ts, src/store/globalStore.test.tsx, src/store/types.ts, src/utils/loaders.test.tsx, src/utils/loaders.ts
- user stored state is rendered in header
- useUserInfo hook and getUserInfoOnce
- stores user information in sessionStorage
- email is deleted from user info before storing
- added userInfoStore
- refactored loaders unit tests
- unit tests
This is required by designers.
=> feat: [P4PU-380] Name and last name in header

src/components/PaymentNotice/Detail.tsx, src/hooks/usePostCarts.test.tsx, src/hooks/usePostCarts.tsx
This pr adds the optional email to the carts api call if available
Passing an email to the carts checkout api, makes the email field 
precompiled once the checkout flow is started
- unit test
=> feat: [P4PU-425] post email to carts

src/routes/Dashboard.tsx, src/translations/it/translations.json
Edited table spacing in dashboard
This change is required by the designers.
=> fix: [P4PU-307] Fixed table spacing.

src/components/Transactions/Transaction.tsx
The arrow is now not shown when on mobile (xs)
This was required by the designers, to allow for more space for other infos.
=> fix: [P4PU-308] Fixed tab rows on mobile.

package.json, src/App.tsx, src/hooks/useUserInfo.test.tsx, src/utils/loaders.test.tsx, src/utils/loaders.ts, yarn.lock
- removed zod mocking from test
- loaders and useUserInfo test refactoring
- added getUserInfoOnce negative test
With this pr api request types are tested
- unit tests
=> feat: [P4PU-397] removed zod mock

src/components/AssistanceForm/AssistanceForm.test.tsx, src/components/AssistanceForm/AssistanceForm.tsx
The PR's goal is to obtain a zendesk token, retrieve the user e-mail and create a new ticket redirecting the user to zendesk
- pre fill the e-mail field
- call the BE to obtain zendesk data
- populate an hidden form to redirect the user
Solve the story P4PU-422
- Unit test
- -visual test
=> feat: [P4PU-369] Refact assistance form

.env, .jest/setup.js, README.md, src/components/Skeleton/TransactionsList.tsx, src/components/Transactions/Transaction.tsx, src/components/Transactions/TransactionDetail.tsx, src/components/Transactions/Transactions.tsx, src/utils/config.test.ts, src/utils/config.tsx
Removed all references to transaction payment status (not required anymore)
Transaction payment status is not required anymore
Tested manually by compiling and running locally the FE
=> feat: [P4PU-348] removing reference to transaction status

src/hooks/useUserInfo.test.tsx, src/hooks/useUserInfo.tsx
- wraps userInfo state update in an effect
Side effect was not handled correctly causing an issue during header update
- visual testing (console no longer prints any errors)
- visit client homepage with dummy token then update
with valid token, refresh and watch for errors in console
- unit test
=> fix: [P4PU-450] effect wraps userInfo update

src/routes/Assistance/Assistance.test.tsx
=> fix: [P4PU-398] fixed assistance test.

src/index.html
Changed title from 'ARC - Area Riservata Cittadino' to 'Area Riservata pagoPA'
This change is required for the demo that will be held on september 12th or 13th.
=> fix: [P4PU-465] Changed title.

.env, src/components/PreLoginLayout.tsx, src/routes/Login/Login.test.tsx, src/routes/Login/index.tsx, src/translations/it/translations.json
- Added a simple and temporary prelogin page (demo purpose)
The entry point will be moved out of the context of this web application. Meanwhile a temporary pre login page in needed (demo and development purpose)
Tested manually trying to login locally with the new pre login page (test succeeded)
=> feat: [P4PU-461] temporary prelogin page, demo purpose

src/components/Sidebar/Sidebar.tsx, src/translations/it/translations.json
This PR fixes the thickness of the header divider when on mobile.
=> fix: [P4PU-310] Fixed header divider thickness.

src/components/PaymentNotice/Card.tsx, src/components/PaymentNotice/Detail.test.tsx
Fixed EC name in payment notices list. It's now the correct value
=> fix: [P4PU-464] Fixed EC name

src/components/PaymentNotice/Detail.test.tsx, src/components/PaymentNotice/Detail.tsx, src/translations/it/translations.json
- replaces iupd with iuv
- unit test update
=> fix: [P4PU-466] displays iuv instead of iupd

.prettierrc, src/routes/Dashboard/Dashboard.test.tsx, src/routes/Dashboard/index.tsx, src/translations/it/translations.json, src/utils/loaders.ts
- Dashboard useUserInfo hook to diplay user.name and user.familyName
- updated dashboard unit tests
- if user is missing the title content is not rendered
This pr replaces the mocked username used previously in the dasboard(home) page
=> feat: [P4PU-467] dashboard user info

src/components/PaymentNotice/List.tsx
Drop overflow hidden when the list is loaded
=> fix: [P4PU-462] Disable overflow on paymentnotices list

.prettierrc, src/components/PaymentNotice/Card.tsx, src/components/PaymentNotice/Detail.test.tsx, src/components/PaymentNotice/Detail.tsx, src/components/Sidebar/Sidebar.tsx, src/routes/Dashboard/Dashboard.test.tsx, src/routes/Dashboard/index.tsx, src/translations/it/translations.json, src/utils/loaders.ts
=> chore: update UAT

src/routes/Dashboard/index.tsx, src/utils/loaders.ts
- added ?size=5 query parameter to the /transactions API call on Dashboard to limit the results
By design, on the initial dashboard only the latest receipts (5) are shown
Tested manually inspecting the network's browser tab and verifying the correctness of the parameter and the response
=> feat: [P4PU-476] adding size=5 to limit the results on dashboard

src/App.tsx, src/components/ApiClient.test.tsx, src/components/ApiClient.tsx, src/components/Header/index.tsx, src/index.tsx, src/models/Client.ts, src/utils/interceptors.test.ts, src/utils/interceptors.ts, src/utils/session.test.ts, src/utils/session.ts
- on 401 clear storage and navigate to courtesy page
- sessionClear to handle storage clear
- setupInterceptors function to set up interceptors
- ApiClient component wraps setupInterceptors logic
- index.tsx interceptors moved to setupInterceptors function
- Client model to represent API client instance
- unit tests
This pr handles 401 status code response, clearing storage and redirecting to the courtesy-page route.
Interceptor setup logic was refactored to enable the possibility of passing Router context to the interceptors
- unit tests
=> feat: [P4PU-436] client 401 interceptor

.devops/deploy-pipelines.yml, .devops/local-templates/setup-env.yaml, src/utils/config.tsx
This PR fixes a warning we had in the console.
=> fix: [P4PU-480] Fixed warning.

src/components/Header/index.tsx
This PR adds the call to the BE service "logout" 
- add call to the service logout
We' ve to notify the logout of a user calling the BE service and clearing the storage
=> feat: [P4PU-435] Call service logout

src/components/AssistanceForm/AssistanceForm.tsx
This PR refact the way to manage input types to avoid sync request to the service
=> fix: [P4PU-469] Fix assistance form

src/hooks/useUserInfo.test.tsx, src/hooks/useUserInfo.tsx, src/models/User.ts
Removed Fiscal code from storage.
=> chore: [P4PU-486] removed cf from storage

src/components/Tabs/index.tsx, src/components/Transactions/Empty.tsx, src/hooks/useNormalizedNoticesList.test.tsx, src/hooks/useNormalizedNoticesList.tsx, src/routes/Dashboard/Dashboard.test.tsx, src/routes/Dashboard/index.tsx, src/routes/NoticesList/NoticesList.test.tsx, src/routes/NoticesList/index.tsx, src/utils/loaders.ts
This PR introduces the filters "paidByMe" and "registeredToMe" now applied BE side through API query parameters:
- filtering FE side removed (see useNormalizedNoticesList in src/hooks)
- filtering BE side introduced (see getNoticesList in src/ultils/loaders)
- unit test update
When these filters weren't available we decided to apply them FE side. 
Now this change is necessary to remove the FE filtering functionality and to introduce it BE side  through API query parameters
Tested on the local development server and through unit tests launching
=> feat: [P4PU-232] paid notices list page, filtering BE side through API query parameters

src/utils/loaders.test.tsx, src/utils/loaders.ts
This PR changes the receipt api pointer.
=> feat: [P4PU-601] New receipt api pointer

src/components/Header/index.tsx
This PR makes it so that the click on the "PagoPA" logo in the header doesn't open a new page.
=> feat: [P4PU-634] edited header's link's target.

src/components/Sidebar/Sidebar.tsx, src/components/Sidebar/sidebar.test.tsx, src/routes/NoticesList/index.tsx, src/translations/it/translations.json
This PR changes the receipt page title according to the new figma.
=> feat: [P4PU-604] Changed page title.

src/components/Transactions/TransactionDetail.tsx, src/components/Transactions/transactionDetail.test.tsx, src/models/NoticeDetail.ts, src/routes/Transaction/Transaction.test.tsx, src/routes/Transaction/index.tsx, src/stories/Transaction/TransactionDetail.stories.tsx, src/stories/utils/mocks.tsx, src/translations/it/translations.json, src/utils/converters.test.ts, src/utils/converters.ts, src/utils/loaders.test.tsx, src/utils/loaders.ts
This PR drop the `transactions` endpoint to set the `notices` one.
- use the new endpoint
- fix the layout
- update translations
Rif. Jira
=> feat: [P4PU-600] New api notices

src/components/Transactions/TransactionDetail.tsx
This PR fixes the title when contains a huge number of chars without any space
- `break-word` css directive
Solve the bug
=> fix: [P4PU-659] Title overflowed

src/translations/it/translations.json
- Cahnges a string mappings
visual testing
=> fix: [P4PU-617] content update

src/components/PaymentNotice/Info.tsx, src/translations/it/translations.json
- removes notices bottom info action
- chages notices bottom info text
- no unit tests update was needed
=> feat: [P4PU-619] Notices bottom info

.env, .proxyrc, src/components/Modals/PullPaymentsModal.tsx, src/components/PaymentNotice/Card.tsx, src/components/PaymentNotice/Detail.tsx, src/components/PaymentNotice/Empty.tsx, src/components/PaymentNotice/Error.tsx, src/components/PaymentNotice/List.tsx, src/components/PaymentNotice/Preview.tsx, src/components/Transactions/Retry.tsx, src/components/Transactions/TransactionDetail.tsx, src/components/Transactions/Transactions.tsx, src/routes/Transaction/index.tsx, src/routes/User/index.tsx
This PR adds id and testid to some element to enhance e2e tests
- change local proxy subpath
- add id & testid
enhance test e2e
=> feat: [P4PU-552]  refine id

src/components/Alerts/Alert.tsx, src/components/Alerts/IOAlert.tsx
- changes dashboard IOAlert component to use the generic Alert component
- IOAlert style is now compatible with the design requirements
- fixes a style issue with the Alert component, fixing its width
Previously the dashboard alert (IOAlert) was not respecting the desgn requirements.
=> feat: [P4PU-681] fixes dashboard and alert styling

.identity/00_data.tf, .identity/99_locals.tf
=> fix: [P4PU-695] e2e test user & pass

.env.dev, .env.test, .env.uat, .github/workflows/e2e.yml, .identity/00_data.tf, .identity/99_locals.tf, README.md, src/components/Footer.tsx, src/utils/config.test.ts, src/utils/config.ts
This PR fixes the not-listened click event on Footer's link.
- drop the unused and conflicting function call `onExit` on the Footer component
Fix the problem
=> fix: [P4PU-663] Drop unused onExit func

src/components/Transactions/TransactionDetail.tsx
Add the word-break attribute to the receipit's title
- add word-break
Solve the issue
=> fix: [P4PU-744] Add word-break to notice title

.github/workflows/pr-title-check.yml
- regex updated in pr-title-check.yml to contemplate titles from renovate's PR
All PR opened automatically by renovate didn't pass the pr title check
Regex tested using [regex101](https://regex101.com/) tool (see the picture below)
=> ci: [P4PU-734] regex updated in PR title check gh action

src/components/Modals/PullPaymentsModal.tsx
Removes tos and pp links from PullPaymentsModal
Visual testing
=> fix: [P4PU-729] removes modal links

src/components/Cart/CartDrawer.styles.tsx, src/components/Cart/CartDrawer.test.tsx, src/components/Cart/CartDrawer.tsx, src/components/Header/SubHeader.test.tsx, src/components/Header/SubHeader.tsx, src/components/Header/index.tsx, src/components/Layout.tsx, src/components/Sidebar/sidebar.styles.ts, src/models/Cart.ts, src/store/CartStore.test.ts, src/store/CartStore.tsx, src/store/GlobalStore.tsx, src/store/types.ts, src/translations/it/translations.json, src/utils/converters.ts, vitest.config.mts
- Replaces mui-italia HeaderProduct
with SubHeader component
- Fixes SubHeader logo Styling
- Adds cart icon to SubHeader
- Adds CartDrawer component
- Handles Cart app state through signals
- Adds localization
- Adds styles files to vitest excluded files
- unit tests
This pr adds the first basis of the cart functionality. Only drawer empty state is considered
- Unit tests
=> feat: [P4PU-716] Cart icon & drawer

src/routes/Dashboard/index.tsx
- IO alert removed from home page (dashboard)
This change is required by design. The component is only removed from dashboard (not deleted completely) and will be reintroduced when a strategic approach is ready
Tested inspecting visually the Front End through the development server
=> feat: [P4PU-786] IO alert removed from dashboard

src/utils/converters.ts
- removes transaction total amount computation from client
- transaction total amount is retrieved from api
=> feat: [P4PU-754] Api notice total amount

.github/workflows/e2e.yml, src/components/Cart/CartDrawer.test.tsx, src/components/Cart/CartDrawer.tsx, src/components/Header/SubHeader.test.tsx, src/components/Header/SubHeader.tsx, src/components/PaymentNotice/Detail.tsx, src/models/Cart.ts, src/models/PaymentNotice.ts, src/store/CartStore.test.ts, src/store/CartStore.tsx, src/utils/storage.ts
- identification and creation of a data structure for the representation of the shopping cart data layer
- identification of all necessary actions to change the cart data structures (add item, delete item, reset cart, etc...)
- cart state persistence through the use of session storage
- unit tests
This PR contains all necessary activities to implement the cart functionality and to progress with the correlated UI elements 
tested through unit tests
=> feat: [P4PU-717] Cart store and actions setup

src/components/Cart/CartDrawer.styles.tsx, src/components/Cart/CartDrawer.tsx, src/components/Header/SubHeader.tsx, src/components/PaymentNotice/Detail.tsx, src/translations/it/translations.json
Several changes (UI and Business Logic) that make possible to have a cart experience, like:
- the add to the cart functionality
- the remove from cart functionality
- new UI component (cart item)
- update to translation file
These changes are preparatory to the cart payment phase
The new functionalities were tested through manual testing and by writing unit tests
=> feat: [P4PU-727] add and remove items to the Cart

src/components/Cart/CartDrawer.styles.tsx, src/components/Cart/CartDrawer.tsx, src/components/Cart/CartItem.tsx, src/components/PaymentNotice/Detail.tsx, src/hooks/usePostCarts.tsx, src/routes/CourtesyPage/index.tsx, src/translations/it/translations.json, src/utils/converters.ts
- refactoring the usePostCarts to make carts.mutation work with multiple items (cart items)
- add error handling for payment process and update translations for error code 422
- disabling pay button when the cart is empty
- minor changes
This is the last necessary change to end the cart functionality. It allows to start a payment using the cart items as source
The whole process (add elements, remove elements, pay the elements) was tested manually using the local development environment
=> feat: [P4PU-728] payment with the cart

src/components/PaymentNotice/Preview.test.tsx, src/components/PaymentNotice/Preview.tsx, src/routes/Dashboard/index.tsx
1. Preview component (payment notices opt-in functionality) always visible on home page (Dashboard)
2. Updating the onClick function on preview component CTA 
This is required by design. The proposed UX was not as expected. This PR fixes the issue and edits the UX
The new UX was tested manually using the local development server
=> fix: [P4PU-770] Preview component (payment notices opt-in) always visible on dashboard 

src/components/Transactions/TransactionDetail.tsx, src/models/NoticeDetail.ts, src/translations/it/translations.json, src/utils/converters.ts
- toggling between download receipt button and missing receipt alert feedback
- minor fixes about layout of elements (css)
- adding a new translation key (transactionDetail.noReceipt)
This is required because sometimes the receipt isn't available (origin == "PM").
When this occurs the user need to know why the receipts is missing (the missing alert added)
The new behaviour, not replicable with real data right now, was tested using mocks as response data and using the local development environment
Receipt available (origin != "PM")
Receipt not available (origin == "PM")
=> feat: [P4PU-765] adding alert feedback when receipt is missing

src/components/PaymentNotice/Card.style.ts, src/components/PaymentNotice/Card.tsx, src/components/PaymentNotice/Detail.tsx, src/components/PaymentNotice/List.tsx
- moves payment card styles to style file
- fixes Payment Detail border radius
- payment card sm style
- payment card xs style
- payments list date info xs style
- removes excessive padding from PaymentDetail xs style
Design requirements
=> fix: [P4PU-773] payments responsivness

src/components/PaymentNotice/Preview.tsx, src/routes/Dashboard/index.tsx
- PaymentButton takes fullwidth on xs resolutions
- "see all" button is aligned to the right instead of below
design requirements
=> fix: [P4PU-774] fixes xs dashboard styles

src/components/Sidebar/sidebar.styles.ts
changes sidebar items container to be sticky
design requirements
visual testing
=> feat: [P4PU-779] makes sidebar items sticky

src/components/Header/index.tsx, src/routes/Dashboard/Dashboard.test.tsx, src/routes/Dashboard/index.tsx, src/routes/User/index.tsx, src/utils/converters.test.ts, src/utils/converters.ts
1. added a new function to utils.converter to forcing capitalize for each first letter of every words in a sentence
2. added unit tests for the new function
3. replaced user name and surname with the output of the function (passing name and surname as parameter)
The user name and surname returned from the BE service aren't in the desired format output (at least not always)
Tested adding unit tests and inspecting the local FE
=> fix: [P4PU-767] forcing capitalize user name and surname

src/components/Sidebar/Sidebar.tsx, src/components/Sidebar/SidebarMenuItem.tsx, src/components/Sidebar/sidebar.styles.ts
changes the sidebar icons padding and alignments, to fix alignments issues
Before this pr icons and seidebar hamburger button were not vertically aligned
visual testing
=> fix: [P4PU-777] side nav alignment

.github/workflows/e2e.yml, src/App.tsx, src/components/Footer.tsx, src/components/PaymentNotice/Card.test.tsx, src/components/Transactions/Transaction.test.tsx, src/routes/AuthCallback/index.tsx, src/routes/CourtesyPage/CourtesyPage.test.tsx, src/routes/CourtesyPage/index.tsx, src/routes/Resources/index.tsx, src/routes/routes.ts, src/utils/interceptors.test.ts, src/utils/interceptors.ts, src/utils/loaders.test.tsx, src/utils/loaders.ts
the URLs has changed in this way:
- '/transactions' -> '/ricevute'
- '/transactions/:id' -> '/ricevute/:id'
- '/user' -> '/profilo'
- '/login' -> '/accesso'
- '/assistance' -> '/assistenza'
- '/courtesy' -> '/errore/:error'
- '/payment-notices' -> '/avvisi'
- '/payment-notices/:id/:paTaxCode' -> '/avvisi/:id/:paTaxCode'
- '/resources?resource=tos' -> '/termini-di-servizio'
-  '/resources?resource=pp' -> '/informativa-privacy'
it was decided to localize the route names in Italian and to choose more appropriate names
Tested through E2E testing and manual testing
=> feat: [P4PU-758] renaming routes

.github/workflows/e2e.yml, src/components/AssistanceForm/AssistanceForm.test.tsx, src/components/AssistanceForm/AssistanceForm.tsx, src/components/RouteGuard/RouteGuard.tsx, src/routes/AuthCallback/index.tsx, src/routes/routes.ts, src/utils/interceptors.test.ts, src/utils/interceptors.ts
- A series of changes that improves the UX of the assistance form
- relative unit test updated
- minor fixes
After a review, the product & design team requested to change and improve the UX of the assistance form
Tested through manual testing and unit tests
=> feat: [P4PU-780] improve form validation in AssistanceForm component

.github/workflows/sonar.yml, src/components/Skeleton/PaymentNoticeDetails.tsx, src/components/Skeleton/TransactionDetails.tsx, src/components/Skeleton/detailsSkeleton.tsx, src/components/Skeleton/index.ts, src/components/Skeleton/skeleton.test.tsx, src/routes/PaymentNoticeDetail/PaymentNoticeDetail.test.tsx, src/routes/PaymentNoticeDetail/index.tsx, src/routes/Transaction/index.tsx
- Recepit details error managment and loading (skeleton)
- Notice details error managment and loading (skeleton)
Giving to the user a feedback about loading phase is a best practice and required by the design. Also managing the errors gives a proper feedback to the user and the possibility to retry
Tested by unit test and manual test (using mocks to replicate errors)
=> feat: [P4PU-833]  receipt and payment notice loading phase and error managment

src/components/Footer.tsx
This PR changes the Footer component and updates a footer link
=> feat: [P4PU-846] update footer link to external privacy portal

.devops/deploy-pipelines.yml, .devops/local-templates/setup-env.yaml, README.md, src/App.tsx, src/components/Header/SubHeader.tsx, src/components/Sidebar/Sidebar.tsx, src/routes/Dashboard/index.tsx, src/utils/config.ts
This PR add a new environment variable (acting as a feature flag) to hide/show the payment notices section and the related cart experience:
- React components updated with proper conditionals
- Routes config object updated with a conditional to exclude/include routes about payment notices
- Deploy pipeline updated to manage the new ENV variable
- README file updated
Payment notices section needs to be disabled in PROD environment, but enabled successively 
Tested trough manual testing, unit test and deploying temporary on DEV environment a version without the payment notices section
=> feat: [P4PU-850] implement conditional rendering for payment notices

src/App.tsx, src/components/AssistanceForm/AssistanceForm.tsx, src/components/Cart/CartDrawer.test.tsx, src/components/Cart/CartDrawer.tsx, src/components/PreLoginLayout.tsx
This PR updated layout for some error pages and for p.p. & t.o.s. page
this is required because the previous layout was not aligned to the product's mockup and guidelines
tested via:
- unit tests
- manual tests
=> fix: [P4PU-848] update routing and error handling in PreLoginLayout

.devops/deploy-pipelines.yml, .devops/local-templates/setup-env.yaml, README.md, src/hooks/usePostCarts.test.tsx, src/translations/it/translations.json, src/utils/config.test.ts, src/utils/config.ts, src/utils/converters.ts
- copy updates
- env variable PAYMENT_RETURN_URL removed
- usePostCarts hook updated with dynamic return urls (ok, ko, cancel)
- Readme file updated accordingly
- unit tests updated
Copy changes and payment return urls were requested for update by P&D team
These minor changes were required by the P&D team and aim to enhance the UX
Tested manually and through unit tests
=> fix: [P4PU-888] payment return URLs updated and minor copy changes

src/routes/NoticesList/index.tsx, src/translations/it/translations.json
- update dependency in useEffect hook in NoticesListPage to include dataUpdatedAt for token validation
- copy updates
this fixes a problem causing the pagination UI disappear in particular circumstances
The only way to test this was via manual testing
=> fix: [P4PU-892] update dependency in NoticesListPage to include dataUpdatedAt for token validation

src/routes/NoticesList/index.tsx
- remove unnecessary console log from NoticesListPage
=> fix: [P4PU-892] remove unnecessary console log from NoticesListPage

.github/workflows/sonar.yml
update SonarCloud GitHub Action to version 5.0.0
prior version was deprecated and causing the GitHub Action fails
see the coverage / sonarcloud check below
=> chore: [P4PU-895] update SonarCloud GitHub Action to version 5.0.0

src/App.tsx, src/components/Footer.test.tsx, src/components/Footer.tsx, src/routes/Login/Login.test.tsx, src/routes/Login/index.tsx
- Component Login automatically redirects to OI or HomePage (according to the access Token)
- Footer component updated with a new link
- Unit test updated
The Login page is not required anymore and is replaced with a Component consisting of pure Logic
Tested via unit tests and manual testing
=> feat: [P4PU-898] remove unused Login component UI and update Footer accessibility link

src/routes/Resources/Resources.test.tsx, src/routes/Resources/index.tsx, src/routes/Resources/resources.css
- added a a custom css to override style coming from onetrust
- removed the draft status to PP e TOS page
=> feat: [P4PU-953] add resources.css for styling and update resource links

.env.dev, .env.uat
- .dev.env file updated (ENV variable added)
- .uat.env file updated (ENV variable added)
These changes are required to avoid E2E tests failure
this was tested running E2E tests locally
=> fix: [P4PU-966] update environment configuration files to include ENV variable for DEV and UAT

src/components/Footer.css, src/components/Footer.tsx, src/components/Header/Header.test.tsx, src/components/Header/index.tsx, src/hooks/useLanguage.test.ts, src/hooks/useLanguage.ts, src/translations/en/translations.json, src/translations/i18n.ts, src/translations/it/translations.json, src/translations/lang.ts
This PR includes:
- a language select in the footer
- an en json file 
- a new entry in Local Storage (i18nextLng)
This is required to make english language available
Tested 'visually' running the FE locally
=> feat: [P4PU-894] lang switcher and ENG translations

src/translations/it/translations.json
This fixes a typo in IT-it translation json file
This  report comes from the Business Simulation phase
Tested 'visually' inspecting the FE running locally
=> fix: [P4PU-951] "Eseguito da" -> "Eseguita da" in IT translations json file

src/translations/en/translations.json, src/translations/it/translations.json
This change updates translation files to append "/IUV" to notice code and increase clarity/readability
This report comes from the Business Simulation phase
Tested 'visually' inspecting the FE running locally
=> fix: [P4PU-952] update translations to include IUV in notice code

src/components/PaymentNotice/Detail.tsx
small style changes about alignments in PaymentNotice detail component
This report comes from the Business Simulation phase
Tested 'visually' inspecting the local FE
=> fix: [P4PU-955] simplify layout and improve spacing in PaymentNotice detail component

src/components/Cart/CartDrawer.styles.tsx, src/components/Cart/CartItem.tsx, src/components/PaymentNotice/Card.tsx
This adds some css rules to avoid layout broke due to uncontrolled long text in cart item and payment notice list item component
This report comes from the Business Simulation phase
This has been tested simulating very long text for cart item and payment notice list item component and inspecting visually the FE at one of the lowest resolution supported (iPhone SE 375x667)
=> fix: [P4PU-954] improve text overflow handling and layout adjustments in CartItem and PaymentNotice components

src/components/Cart/CartDrawer.styles.tsx, src/components/Cart/CartItem.tsx, src/components/PaymentNotice/Detail.tsx
This PR fix a bug that was causing a problem with items deletion when the cart reaches its limit (five items).
Some minor style changes fix a layout problem in the cart drawer component on lower resolutions.
This report comes from the Business Simulation phase
Tested manually on the local develop environment
=> fix: [P4PU-958] fixing a problem with the maximum cart items and item deletion

src/components/Footer.tsx, src/translations/fr/translations.json, src/translations/lang.ts
This PR adds:
- a french json file
- a new entry into language select placed in the footer
This is required to make french language available
Tested 'visually' running the FE locally
=> feat: [P4PU-964] french translations

package.json, src/components/Header/Header.test.tsx, src/components/Header/index.tsx, src/translations/en/translations.json, src/translations/fr/translations.json, src/translations/it/translations.json, yarn.lock
- update @pagopa/mui-italia to version 1.5.3
- add help translations in header
This missing translation completes the localization activity
Tested visually changing the language and inspecting the FE
=> feat: [P4PU-945] update @pagopa/mui-italia to version 1.5.3 and add help translations in header

sonar-project.properties, src/App.tsx, src/components/ErrorFallback/ErrorFallback.test.tsx, src/components/ErrorFallback/ErrorFallback.tsx, src/components/RouteGuard/RouteGuard.tsx, src/routes/CourtesyPage/CourtesyPage.test.tsx, src/routes/CourtesyPage/index.tsx, src/routes/routes.ts, src/translations/en/translations.json, src/translations/fr/translations.json, src/translations/it/translations.json
- 400 error management (generic unknown error)
- 404 error management (resource not found)
This improves the error management discriminating the 400 from the 404 error
Tested trough manual testing simulating several errors
=> feat: [P4PU-968] implement error handling and routing improvements with new error pages and translations

src/App.tsx
Updated the routing config to handle the redirect to dashboard and avoiding the 404 route page
This fix is required because without it the user will be not redirected to the dashboard if the navigation starts from '/' 
Tested manually
=> fix: [P4PU-972] redirect to the dashboard
