pagopa/arc-fe

- src/components/Footer.tsx
- src/components/Header.tsx
- src/components/Layout.tsx
- src/components/Sidebar/Sidebar.tsx
- src/utils/config.tsx
- src/utils/index.ts
- src/utils/style.tsx
With this PR the Header componet taken from mui library is introduced in the main layout. 
It's a static component without logic and it will be necessary to introduce them in a more advanced phase of the project (
e.g: by valorising the username when we have the login functionality available)
Of course the Header component is a required one and needs to be introduced
Tested running the FE locally and comparing it with its relative design
> feat: [P4ADEV-165] header component

- src/components/PaymentNotice/PaymentNotice.tsx
- src/components/PaymentNotice/Preview.test.tsx
- src/components/PaymentNotice/Preview.tsx
- src/components/PaymentNotice/index.tsx
- src/routes/Dashboard.tsx
- src/stories/PaymentNotice.stories.tsx
- src/translations/it/translations.json
- PaymentNotice.Preview component
- Adds PaymentNotice.Preview to dashboard page
- PaymentNotice.Preview stories
- PaymentNotice.Preview unit tests
- PaymentNotice.Preview i18n for 'it' locale
This pr creates the PaymentNotice.Preview component and related stories.
This component is rendered inside the Dashboard route.
- Visual Testing
- Storybook
- Unit tests
> feat: [P4PU-178] payment notice preview

- src/App.tsx
- src/components/Layout.tsx
- src/components/PayeeIcon/PayeeIcon.tsx
- src/components/PayeeIcon/index.ts
- src/components/PaymentNotice/Card.test.tsx
- src/components/PaymentNotice/Card.tsx
- src/components/PaymentNotice/PaymentNotice.tsx
- src/components/PaymentNotice/Preview.tsx
- src/components/Transactions/Transaction.tsx
- src/routes/PaymentNotices.tsx
- src/routes/routes.ts
- src/stories/PaymentNotice.stories.tsx
- src/translations/it/translations.json
- src/utils/style.tsx
- Adds PaymentNotice.Card component
- Adds PaymentNotices component
- Adds PaymentNotices to routing
- PaymentNotice.Card stories
- Reafctored PayeeIcon as a separate component
- i18n for PaymentNotices and PaymentNotice.Card
- unit tests
Adds a route showing all the user payment notice. All data rendered in this pr is static.
- Unit tests
- Storybook stories
> feat: [P4PU-180] payment notices route

- src/components/PaymentNotice/Info.test.tsx
- src/components/PaymentNotice/Info.tsx
- src/components/PaymentNotice/PaymentNotice.tsx
- src/components/QueryLoader/index.tsx
- src/components/QueryLoader/queryLoader.test.tsx
- src/components/Skeleton/PaymentNoticesList.tsx
- src/components/Skeleton/index.ts
- src/components/Skeleton/skeleton.test.tsx
- src/routes/Dashboard.tsx
- src/routes/PaymentNotices.tsx
- src/routes/TransactionsList.tsx
- src/translations/it/translations.json
- src/utils/loaders.ts
- Refactor of the Query Loader component
- Creation of the payment notices skeleton layout 
- Adding a fake loading time to the payment notices page
To allow the waiting message to be read (which would be impossible if the API responded very quickly) it is necessary to simulate a minimum waiting time
Tested locally through local development server
> feat: [P4PU-212] payment notices page skeleton and  fake loading time

- src/components/Sidebar/Sidebar.tsx
- src/components/Sidebar/SidebarMenuItem.tsx
- src/components/Sidebar/sidebar.styles.ts
- src/components/Sidebar/sidebar.test.tsx
- src/hooks/useCollapseMenu.test.tsx
- src/hooks/useCollapseMenu.tsx
- moved sidebar styles in its own file
- sidebar collapse/expand transitions
- useCollapseMenu refactoring
- useCollapseMenu state changes when crossing lg(1200px) threshold
- unit tests
This pr tries to improves sidebar responsiveness. The previous useCollapseMenu behavior was to keep the current state when changing resolutions resulting in a weird user experience.
Also some transition animation was added to decrease ui jank when crossing resolution threshold.
- unit tests
> feat: [P4PU-207] sidebar responsiveness

- src/components/PaymentNotice/Detail.test.tsx
- src/components/PaymentNotice/Empty.test.tsx
- src/components/PaymentNotice/Info.test.tsx
- src/components/PaymentNotice/Preview.test.tsx
- src/hooks/useNormalizedNotices.test.tsx
- src/hooks/usePersistentSignal.test.ts
- src/hooks/usePersistentSignal.ts
- src/routes/PaymentNoticeDetail.tsx
- src/store/GlobalStore.tsx
- src/store/PaymentNoticeStore.tsx
- src/store/globalStore.test.tsx
With this PR landing on /payment-notice/:`id` redirect to /payment-notices if `id` is not equal to the notice `iupd`.
Moreover, the stored PaymentNotice is removed from `localStorage` if this situation occurs.  
Before this changes the last stored PayementNotice was rendered with any id value to /payment-notices/:id
- unit tests
> feat: [P4PU-341] Redirect on PaymentNotice mismatch

- src/components/Layout.tsx
Fix the scroll when navigate between pages.
- add `ScrollRestoration` hook as suggested by the react-router-dom doc
When a user navigate from list to detail, the overflow must be restored to the top as usual
> fix: [P4PU-309] Fix scroll behavior

- src/components/Sidebar/Sidebar.tsx
- src/components/Sidebar/SidebarMenuItem.tsx
- src/models/SidebarMenuItem.ts
This PR solve the issue: Sidebar button homepage "always on"
- Add "end attribute" to manage when we want a button selected only in an exact path (es Homepage)
> fix: [P4PU-444] Sidebar button homepage "always on"

- package.json
- src/components/Header/Header.test.tsx
- src/components/PaymentNotice/Detail.test.tsx
- src/components/PaymentNotice/Empty.test.tsx
- src/components/PaymentNotice/Info.test.tsx
- src/components/PaymentNotice/Preview.test.tsx
- src/routes/PaymentNotices/PaymentNotices.test.tsx
- src/store/PaymentNoticeStore.test.tsx
- src/store/UserInfoStore.test.ts
- src/store/globalStore.test.tsx
- src/utils/loaders.test.tsx
- vitest.setup.mts
- yarn.lock
- removes vitest setup signal mocking
- removes signals  mocks where superflous
- increases store provider coverage
- signals library dependency upgraded
Using vitest and the latest version of @preact/signals, the library mock is not needed anymore
unit testing
> fix: [P4PU-349] signals unmocked and tested

- src/components/PaymentNotice/Card.tsx
- src/components/PaymentNotice/Error.test.tsx
- src/components/PaymentNotice/Error.tsx
- src/routes/PaymentNotices/PaymentNotices.test.tsx
- src/routes/PaymentNotices/index.tsx
- vitest.setup.mts
1. Adding a e.stopPropagation to avoid a multiple calling to navigate (fix the problem about the necessity to click two times back to return to the list from the detail notice page)
2. Adding a retry function (missing) to the retry button on payment notices page
3. Clearing the SessionStorage item paymentNotice on payment notices page return (no need to keep data outside the scope of the detail page)
Writing E2E test about the list and detail notice page these have been discovered and fixed with this PR to make E2E test run successfully
Manually trying to replicate the problems and running the relative E2E test (locally)
> fix: [P4PU-565] back from notice detail, retry on error and paymentNotice SessionStorage clearing

- src/components/Transactions/TransactionDetail.tsx
- src/components/Transactions/transactionDetail.test.tsx
- src/translations/it/translations.json
- src/utils/files.test.ts
- src/utils/files.ts
This PR handles the error that the receipt fetching function can throw, and shows a toast accordingly.
> feat: [P4PU-585] added receipt error toast.

- .proxyrc
- src/routes/AuthCallback/index.tsx
- src/routes/CourtesyPage/CourtesyPage.test.tsx
- src/routes/CourtesyPage/index.tsx
- src/translations/it/translations.json
- src/utils/loaders.test.tsx
- src/utils/loaders.ts
This PR create an unhappy path for the login service redirecting the user to the courtesy page.
- add the Error management to the login call
- add a more reliable courtesy page
Try to have a specific management for unhappy cases when the user try to access
- unit test
- manual test
> feat: [P4PU-586] Unhappy path for login flow

- src/routes/CourtesyPage/index.tsx
- src/translations/it/translations.json
- src/utils/interceptors.ts
- src/utils/loaders.ts
This PR fixes the un managed "empty" response from OI endpoint.
- add a default value `408` to manage an empty response
- edit the translation file to alert the user in Courtesypage
The endpoint of OI can drop the connection sometime.
> fix: [P4PU-643] token malformed response

- package.json
- src/components/Alerts/Alert.test.tsx
- src/components/Alerts/Alert.tsx
- src/routes/PaymentNotices/index.tsx
- src/translations/it/translations.json
- yarn.lock
- updates mui-italia dependency
- adds Alert component
- add an InfoAlert for the PaymentNotices
- adds required strings to the it langmap
- unit tests
Adds a previously missing alert as specified from requirements. Creates a generic Alert component with updated style from the design requirements
- unit tests
> feat: [P4PU-618] Notices Alert component

- src/components/Transactions/Transactions.tsx
- src/hooks/useNormalizedNoticesList.test.tsx
- src/hooks/useNormalizedNoticesList.tsx
- src/routes/Dashboard/index.tsx
- src/routes/NoticesList/NoticesList.test.tsx
- src/routes/NoticesList/index.tsx
- src/utils/loaders.test.tsx
- src/utils/loaders.ts
- This PR adds pagination to the notices list and a toggle to change the order by date from ascendent to descendent and vice versa. 
- All unit tests involved were updated. 
- Some interfaces received a minor but required update.
We were displaying all items available because the involved API didn't allow pagination
Tested automatically updating all unit tests involved and manually testing the local FE
> feat: [P4PU-599] Notices list pagination

- .env
- .env.dev
- .env.test
- .env.uat
- .github/workflows/e2e.yml
- .identity/99_locals.tf
- README.md
- src/utils/config.test.ts
- src/utils/config.ts
- environment removed from e2e.yml action
- using repository secretes instead of environment secrets (E2E_USERNAME, E2E_PASSWORD)
- added a .env.dev file to execute E2E tests pointing at DEV environment
- added a .env.uat file to execute E2E tests pointing at UAT environment
using github environments implies a deployment. This is not the case: the E2E test action does not perform any deployment or environment updates. For this reason I preferred not to use environments, at least until the problem is resolved on the github side. For more info: https://github.com/actions/runner/issues/2120
In the checks section below, the E2E test step is executed correctly and no deployment is added
> ci: [P4PU-695] using dedicated .env file instead of using environments

- src/App.tsx
- src/components/AssistanceForm/AssistanceForm.tsx
This PR drops the back button on the Assistance form page.
- remove back link from route setting
- remove button from the page
Solve the request
> fix: [P4PU-666] Drop back button on assistance form

- src/components/Transactions/NoData.test.tsx
- src/components/Transactions/NoData.tsx
- src/routes/NoticesList/NoticesList.test.tsx
- src/routes/NoticesList/index.tsx
- src/translations/it/translations.json
- translation file (it) updated
- NoData component updated (prop title and text added)
Design has changed and consequentially an updated to the codebase is required
Tested manually mocking the response from the /notices API (to have an empty notices array as result) and inspecting the output with the design
> feat: [P4PU-747] payment notices, no data feedback updated

- src/App.tsx
- src/components/Footer.test.tsx
- src/components/Footer.tsx
- src/routes/Resources/index.tsx
This OR includes:
- Footer refactoring
- footer links opens in a new tab
- updated TOS and PP onetrust resource links
The PP e TOS pages needs to be available to all users and not only to logged ones
Tested manually and running unit tests
> feat: [P4PU-884] footer refactored and TOS and PP available again to unlogged user

- src/App.tsx
- src/routes/CourtesyPage/CourtesyPage.test.tsx
- src/routes/CourtesyPage/index.tsx
- Update CourtesyPage routing and error handling to use useParams instead of useLoaderData
This fix a bug that was causing an infinte redirect loop on courtesy page
> fix: [P4PU-970] update CourtesyPage routing and error handling to use useParams instead of useLoaderData

- package.json
- src/components/PaymentNotice/Detail.tsx
- src/components/Sidebar/Sidebar.tsx
- src/components/Transactions/TransactionDetail.tsx
- yarn.lock
- @pagopa/mui-italia dependecy updated from 1.5.3 to 1.6.1 version
- color fixed and aligned to the design in CopyToClipboardButton component
This is required because a previous mui-italia dependency update caused an wrong color visualization for some icons
Tested by manual visual inspection
> fix: [P4PU-971] copyToClipBoard icon color fix
